<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\tModLoader.targets" />
	
	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>
	
	<ItemGroup>
		<Reference Include="Fargowiltas">
			<HintPath>lib\Fargowiltas.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="FargowiltasSouls">
			<HintPath>lib\FargowiltasSouls.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Luminance">
			<HintPath>lib\Luminance.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<ProjectReference Include="..\Monochrome\Monochrome.csproj" />
	</ItemGroup>
	<ItemGroup>
		<AdditionalFiles Include="**/*.csv" />
	</ItemGroup>

</Project>
